version: 1.0.{build}
image: Visual Studio 2022

configuration: Release

init:
  - git config --global core.autocrlf false

before_build:
  - ps: 'if (($env:APPVEYOR_REPO_TAG -eq "true") -and ($env:APPVEYOR_REPO_TAG_NAME -match "^nobuild"))
    {
      echo "Skipping build, because the tag has the ''nobuild'' prefix.";
      Exit-AppVeyorBuild;
    }'
  - dotnet restore src/TypeGen/TypeGen.Cli
  - dotnet restore src/TypeGen/TypeGen.Core
  - dotnet restore src/TypeGen/TypeGen.Cli.Test
  - dotnet restore src/TypeGen/TypeGen.Core.Test
  - dotnet restore src/TypeGen/TypeGen.FileContentTest

build:
  project: src/TypeGen/TypeGen.sln
  
after_test:
  - ps: ./publish.ps1 -nobuild
  
artifacts:
  - path: '*.nupkg'
    name: NuGet packages
  
deploy:
  provider: NuGet
  api_key:
    secure: hlPXdsDMIeQzAdvV3tnuHMcBnYsbMecgLfVB6TYc1r5NuU7Wizc8y1QPqF/vxjxR
  skip_symbols: true
  on:
    branch: master
    APPVEYOR_REPO_TAG: true